<?php
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("abide", "abode", "abode", "respecter / se conformer à", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("arise", "arose", "arisen", "survenir", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("awake", "awoke", "awoken", "se réveiller", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("be", "was, were", "been", "être", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bear", "bore", "borne / born", "porter / supporter / naître", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("beat", "beat", "beaten", "battre", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("become", "became", "become", "devenir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("beget", "begat / begot", "begotten", "engendrer", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("begin", "began", "begun", "commencer", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bend", "bent", "bent", "plier / se courber", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bereave", "bereft / bereaved", "bereft / bereaved", "déposséder / priver", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bet", "bet", "bet", "parier", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bid", "bid / bade", "bid / bidden", "offrir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bind", "bound", "bound", "lier", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bite", "bite", "bitten", "mordre", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bleed", "bled", "bled", "saigner", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("blow", "blew", "blown", "souffler / gonfler", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("break", "broke", "broken", "casser", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("breed", "bred", "bred", "élever (des animaux)", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bring", "brought", "brought", "apporter", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("broadcast", "broadcast", "broadcast", "diffuser / émettre", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("build", "built", "built", "construire", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("burn", "burnt / burned", "burnt / burned", "brûler", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("burst", "burst", "burst", "éclater", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("buy", "bought", "bought", "acheter", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("can", "could", "could", "pouvoir", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("cast", "cast", "cast", "jeter / distribuer (rôles)", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("catch", "caught", "caught", "attraper", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("chide", "chid", "chiden", "gronder", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("choose", "chose", "chosen", "choisir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("cling", "clung", "clung", "s\'accrocher", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("clothe", "clad / clothed", "clad / clothed", "habiller / recouvrir", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("come", "came", "come", "venir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("cost", "cost", "cost", "coûter", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("creep", "crept", "crept", "ramper", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("cut", "cut", "cut", "couper", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("deal", "dealt", "dealt", "distribuer", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("dig", "dug", "dug", "creuser", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("dive", "dived", "dived / dove", "plonger", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("do", "did", "done", "faire", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("draw", "drew", "drawn", "dessiner / tirer", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("dream", "dreamt / dreamed", "dreamt / dreamed", "rêver", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("drink", "drank", "drunk", "boire", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("drive", "drove", "driven", "conduire", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("dwell", "dwelt", "dwelt / dwelled", "habiter", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("eat", "ate", "eaten", "manger", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("fall", "fell", "fallen", "tomber", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("feed", "fed", "fed", "nourrir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("feel", "felt", "felt", "se sentir / ressentir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("fight", "fought", "fought", "se battre", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("find", "found", "found", "trouver", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("flee", "fled", "fled", "s\'enfuir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("fling", "flung", "flung", "lancer", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("fly", "flew", "flown", "voler", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("forbid", "forbade", "forbidden", "interdire", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("forecast", "forecast", "forecast", "prévoir", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("foresee", "foresaw", "foreseen", "prévoir / présentir", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("forget", "forgot", "forgotten / forgot", "oublier", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("forgive", "forgave", "forgiven", "pardonner", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("forsake", "forsook", "forsaken", "abandonner", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("freeze", "froze", "frozen", "geler", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("get", "got", "gotten / got", "obtenir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("give", "gave", "given", "donner", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("go", "went", "gone", "aller", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("grind", "ground", "ground", "moudre / opprimer", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("grow", "grew", "grown", "grandir / pousser", 1)');

$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("hang", "hung", "hung", "tenir / pendre", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("have", "had", "had", "avoir", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("hear", "heard", "heard", "entendre", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("heave", "hove", "hove", "lever", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("hide", "hid", "hidden", "cacher", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("hit", "hit", "hit", "taper / appuyer", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("hold", "held", "held", "tenir", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("hurt", "hurt", "hurt", "blesser", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("keep", "kept", "kept", "garder", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("kneel", "knelt", "knelt", "s\'agenouiller", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("knit", "knit", "knit", "tricoter", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("know", "knew", "known", "connaître / savoir", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("lay", "laid", "laid", "poser", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("lead", "led", "led", "mener / guider", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("lean", "leant / leaned", "leant / leaned", "s\'incliner / se pencher", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("leap", "leapt / leaped", "leapt / leaped", "sauter / bondir", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("learn", "learnt", "learnt", "apprendre", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("leave", "left", "left", "laisser / quitter / partir", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("lend", "lent", "lent", "prêter", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("let", "let", "let", "permettre / louer", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("lie", "lay", "lain", "s\'allonger", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("light", "lit / lighted", "lit / lighted", "allumer", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("lose", "lost", "lost", "perdre", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("make", "made", "made", "fabriquer", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("mean", "meant", "meant", "signifier", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("meet", "met", "met", "rencontrer", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("mow", "mowed", "mowed / mown", "tondre", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("offset", "offset", "offset", "compenser", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("overcome", "overcame", "overcome", "surmonter", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("partake", "partook", "partaken", "prendre part à", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("pay", "paid", "paid", "payer", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("plead", "pled / pleaded", "pled / pleaded", "supplier / plaider", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("preset", "preset", "preset", "programmer", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("prove", "proved", "proven / proved", "prouver", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("put", "put", "put", "mettre", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("quit", "quit", "quit", "quitter", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("read", "read", "read", "lire", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("relay", "relaid", "relaid", "relayer", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("rend", "rent", "rent", "déchirer", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("rid", "rid", "rid", "débarrasser", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("ride", "rode", "ridden", "monter (vélo, cheval)", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("ring", "rang", "rung", "sonner / téléphoner", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("rise", "rose", "risen", "lever", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("run", "ran", "run", "courir", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("saw", "saw / sawed", "sawn / sawed", "scier", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("say", "said", "said", "dire", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("see", "saw", "seen", "voir", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("seek", "sought", "sought", "chercher", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sell", "sold", "sold", "vendre", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("send", "sent", "sent", "envoyer", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("set", "set", "set", "fixer", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sew", "sewed", "sewn", "coudre", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shake", "shook", "shaken", "secouer", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shear", "sheared", "shorn", "tondre", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shed", "shed", "shed", "répandre / laisser tomber", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shine", "shone", "shone", "briller", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shoe", "shod", "shod", "chausser", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shoot", "shot", "shot", "tirer / fusiller", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("show", "showed", "shown", "montrer", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shrink", "shrank / shrunk", "shrunk / shrunk", "(se) contracter / (se) rétrécir", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shut", "shut", "shut", "fermer", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sing", "sang", "sung", "chanter", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sink", "sank / sunk", "sunk / sunken", "couler", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sit", "sat", "sat", "s\'asseoir", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("slay", "slew", "slain", "tuer", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sleep", "slept", "slept", "dormir", 2)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("slide", "slid", "slid", "glisser", 2)');

$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sling", "slung", "slung", "lancer", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("slink", "slunk / slinked", "slunk / slinked", "s\'en aller furtivement", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("slit", "slit", "slit", "fendre", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("smell", "smelt", "smelt", "sentir", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sow", "sowed", "sown / sowed", "semer", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("speak", "spoke", "spoken", "parler", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("speed", "sped", "sped", "aller vite", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spell", "spelt", "spelt", "épeler / orthographier", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spend", "spent", "spent", "dépenser / passer du temps", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spill", "spilt / spilled", "spilt / spilled", "renverser", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spin", "spun", "spun", "tourner / faire tourner", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spit", "spat / spit", "spat / spit", "cracher", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("split", "split", "split", "fendre", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spoil", "spoilt", "spoilt", "gâcher / gâter", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spread", "spread", "spread", "répandre", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spring", "sprang", "sprung", "surgir / jaillir / bondir", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("stand", "stood", "stood", "être debout", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("steal", "stole", "stolen", "voler / dérober", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("stick", "stuck", "stuck", "coller", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sting", "stung", "stung", "piquer", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("stink", "stank", "stunk", "puer", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("strew", "strewed", "strewn / strewed", "éparpiller", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("strinde", "strode", "stridden / strode", "marche à grand pas", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("strike", "struck", "stricken / struck", "frapper", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("string", "strung", "strung", "ficeler", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("strive", "strove", "striven", "s\'efforcer", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("swear", "swore", "sworn", "jurer", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sweat", "sweat / sweated", "sweat / sweated", "suer", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sweep", "swept", "swept", "balayer", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("swell", "swelled", "swollen / swelled", "gonfler / enfler", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("swim", "swam", "swum", "nager", 5)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("swing", "swung", "swung", "balancer", 5)');

$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("take", "took", "taken", "prendre", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("teach", "taught", "taught", "enseigner", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("tear", "tore", "torn", "déchirer", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("tell", "told", "told", "dire / raconter", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("think", "thought", "thought", "penser", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("thrive", "throve / thrived", "thriven / thrived", "prospérer", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("throw", "threw", "thrown", "jeter", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("thrust", "thrust", "thrust", "enfoncer", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("tread", "trod", "trodden", "piétiner quelque chose", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("typeset", "typeset", "typeset", "composer", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("undergo", "underwent", "undergone", "subir", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("understand", "understood", "understood", "comprendre", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("wake", "woke", "woken", "réveiller", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("wear", "wore", "worn", "porter (avoir sur soi)", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("weave", "wove", "woven", "tisser / tresser / tituber", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("wed", "wed", "wed", "épouser / marier", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("weep", "wept", "wept", "pleurer", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("wet", "wet / wetted", "wet / wetted", "mouiller", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("win", "won", "won", "gagner", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("wind", "wound", "wound", "enrouler / remonter", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("withdraw", "withdrew", "withdrawn", "se retirer", 7)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("wring", "wrung", "wrung", "tordre", 6)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("write", "wrote", "written", "écrire", 6)');
