<?php
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("abide", "abode", "abode", "respecter / se conformer à")');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("arise", "arose", "arisen", "survenir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("awake", "awoke", "awoken", "se réveiller", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("be", "was, were", "been", "être", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bear", "bore", "borne / born", "porter / supporter / naître", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("beat", "beat", "beaten", "battre", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("become", "became", "become", "devenir", 1)');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("beget", "begat / begot", "begotten", "engendrer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("begin", "began", "begun", "commencer", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bend", "bent", "bent", "plier / se courber", 1)');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bereave", "bereft / bereaved", "bereft / bereaved", "déposséder / priver")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bet", "bet", "bet", "parier", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bid", "bid / bade", "bid / bidden", "offrir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bind", "bound", "bound", "lier", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bite", "bite", "bitten", "mordre", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bleed", "bled", "bled", "saigner", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("blow", "blew", "blown", "souffler / gonfler", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("break", "broke", "broken", "casser", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("breed", "bred", "bred", "élever (des animaux)", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("bring", "brought", "brought", "apporter", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("broadcast", "broadcast", "broadcast", "diffuser / émettre", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("build", "built", "built", "construire", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("burn", "burnt / burned", "burnt / burned", "brûler", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("burst", "burst", "burst", "éclater", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("buy", "bought", "bought", "acheter", 1)');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("can", "could", "could", "pouvoir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("cast", "cast", "cast", "jeter / distribuer (rôles)", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("catch", "caught", "caught", "attraper", 1)');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("chide", "chid", "chiden", "gronder")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("choose", "chose", "chosen", "choisir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("cling", "clung", "clung", "s\'accrocher", 1)');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("clothe", "clad / clothed", "clad / clothed", "habiller / recouvrir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("come", "came", "come", "venir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("cost", "cost", "cost", "coûter", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("creep", "crept", "crept", "ramper", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("cut", "cut", "cut", "couper", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("deal", "dealt", "dealt", "distribuer", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("dig", "dug", "dug", "creuser", 1)');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("dive", "dived", "dived / dove", "plonger")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("do", "did", "done", "faire", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("draw", "drew", "drawn", "dessiner / tirer", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("dream", "dreamt / dreamed", "dreamt / dreamed", "rêver", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("drink", "drank", "drunk", "boire", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("drive", "drove", "driven", "conduire", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("dwell", "dwelt", "dwelt / dwelled", "habiter", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("eat", "ate", "eaten", "manger", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("fall", "fell", "fallen", "tomber", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("feed", "fed", "fed", "nourrir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("feel", "felt", "felt", "se sentir / ressentir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("fight", "fought", "fought", "se battre", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("find", "found", "found", "trouver", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("flee", "fled", "fled", "s\'enfuir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("fling", "flung", "flung", "lancer", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("fly", "flew", "flown", "voler", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("forbid", "forbade", "forbidden", "interdire", 1)');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("forecast", "forecast", "forecast", "prévoir")');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("foresee", "foresaw", "foreseen", "prévoir / présentir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("forget", "forgot", "forgotten / forgot", "oublier", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("forgive", "forgave", "forgiven", "pardonner", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("forsake", "forsook", "forsaken", "abandonner", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("freeze", "froze", "frozen", "geler", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("get", "got", "gotten / got", "obtenir", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("give", "gave", "given", "donner", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("go", "went", "gone", "aller", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("grind", "ground", "ground", "moudre / opprimer", 1)');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("grow", "grew", "grown", "grandir / pousser", 1)');

$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("hang", "hung", "hung", "tenir / pendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("have", "had", "had", "avoir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("hear", "heard", "heard", "entendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("heave", "hove", "hove", "lever")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("hide", "hid", "hidden", "cacher")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("hit", "hit", "hit", "taper / appuyer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("hold", "held", "held", "tenir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("hurt", "hurt", "hurt", "blesser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("keep", "kept", "kept", "garder")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("kneel", "knelt", "knelt", "s\'agenouiller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("knit", "knit", "knit", "tricoter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("know", "knew", "known", "connaître / savoir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("lay", "laid", "laid", "poser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("lead", "led", "led", "mener / guider")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("lean", "leant / leaned", "leant / leaned", "s\'incliner / se pencher")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("leap", "leapt / leaped", "leapt / leaped", "sauter / bondir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("learn", "learnt", "learnt", "apprendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("leave", "left", "left", "laisser / quitter / partir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("lend", "lent", "lent", "prêter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("let", "let", "let", "permettre / louer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("lie", "lay", "lain", "s\'allonger")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("light", "lit / lighted", "lit / lighted", "allumer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("lose", "lost", "lost", "perdre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("make", "made", "made", "fabriquer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("mean", "meant", "meant", "signifier")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("meet", "met", "met", "rencontrer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("mow", "mowed", "mowed / mown", "tondre")');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("offset", "offset", "offset", "compenser")');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("overcome", "overcame", "overcome", "surmonter")');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("partake", "partook", "partaken", "prendre part à")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("pay", "paid", "paid", "payer")');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("plead", "pled / pleaded", "pled / pleaded", "supplier / plaider")');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("preset", "preset", "preset", "programmer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("prove", "proved", "proven / proved", "prouver")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("put", "put", "put", "mettre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("quit", "quit", "quit", "quitter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("read", "read", "read", "lire")');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("relay", "relaid", "relaid", "relayer")');
//$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("rend", "rent", "rent", "déchirer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("rid", "rid", "rid", "débarrasser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("ride", "rode", "ridden", "monter (vélo, cheval)")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("ring", "rang", "rung", "sonner / téléphoner")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("rise", "rose", "risen", "lever")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("run", "ran", "run", "courir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("saw", "saw / sawed", "sawn / sawed", "scier")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("say", "said", "said", "dire")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("see", "saw", "seen", "voir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("seek", "sought", "sought", "chercher")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sell", "sold", "sold", "vendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("send", "sent", "sent", "envoyer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("set", "set", "set", "fixer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sew", "sewed", "sewn", "coudre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shake", "shook", "shaken", "secouer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shear", "sheared", "shorn", "tondre")');



$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shed", "shed", "shed", "répandre / laisser tomber")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shine", "shone", "shone", "briller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shoe", "shod", "shod", "chausser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shoot", "shot", "shot", "tirer / fusiller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("show", "showed", "shown", "montrer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("shut", "shut", "shut", "fermer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sing", "sang", "sung", "chanter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sink", "sank / sunk", "sunk / sunken", "couler")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sit", "sat", "sat", "s\'asseoir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("slay", "slew", "slain", "tuer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sleep", "slept", "slept", "dormir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("slide", "slid", "slid", "glisser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("slink", "slunk / slinked", "slunk / slinked", "s\'en aller furtivement")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("slit", "slit", "slit", "fendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("smell", "smelt", "smelt", "sentir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sow", "sowed", "sown / sowed", "semer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("speak", "spoke", "spoken", "parler")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("speed", "sped", "sped", "aller vite")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spell", "spelt", "spelt", "épeler / orthographier")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spend", "spent", "spent", "dépenser / passer du temps")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spill", "spilt / spilled", "spilt / spilled", "renverser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spin", "spun", "spun", "tourner / faire tourner")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spit", "spat / spit", "spat / spit", "cracher")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("split", "split", "split", "fendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spoil", "spoilt", "spoilt", "gâcher / gâter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spread", "spread", "spread", "répandre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("spring", "sprang", "sprung", "surgir / jaillir / bondir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("stand", "stood", "stood", "être debout")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("steal", "stole", "stolen", "voler / dérober")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("stick", "stuck", "stuck", "coller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sting", "stung", "stung", "piquer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("stink", "stank", "stunk", "puer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("strew", "strewed", "strewn / strewed", "éparpiller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("strike", "struck", "stricken / struck", "frapper")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("strive", "strove", "striven", "s\'efforcer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("swear", "swore", "sworn", "jurer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sweat", "sweat / sweated", "sweat / sweated", "suer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("sweep", "swept", "swept", "balayer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("swell", "swelled", "swollen / swelled", "gonfler / enfler")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("swim", "swam", "swum", "nager")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("swing", "swung", "swung", "se balancer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("take", "took", "taken", "prendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("teach", "taught", "taught", "enseigner")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("tear", "tore", "torn", "déchirer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("tell", "told", "told", "dire / raconter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("think", "thought", "thought", "penser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("thrive", "throve / thrived", "thriven / thrived", "prospérer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("throw", "threw", "thrown", "jeter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("thrust", "thrust", "thrust", "enfoncer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("tread", "trod", "trodden", "piétiner quelque chose")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("typeset", "typeset", "typeset", "composer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("undergo", "underwent", "undergone", "subir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("understand", "understood", "understood", "comprendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("wake", "woke", "woken", "réveiller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("wear", "wore", "worn", "porter (avoir sur soi)")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("weep", "wept", "wept", "pleurer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("wet", "wet / wetted", "wet / wetted", "mouiller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("win", "won", "won", "gagner")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("wind", "wound", "wound", "enrouler / remonter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("withdraw", "withdrew", "withdrawn", "se retirer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("wring", "wrung", "wrung", "tordre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french, page) VALUES("write", "wrote", "written", "écrire")');
