<?php
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("abide", "abode", "abode", "respecter / se conformer à")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("arise", "arose", "arisen", "survenir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("awake", "awoke", "awoken", "se réveiller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("be", "was, were", "been", "être")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("bear", "bore", "borne / born", "porter / supporter / naître")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("beat", "beat", "beaten", "battre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("become", "became", "become", "devenir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("beget", "begat / begot", "begotten", "engendrer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("begin", "began", "begun", "commencer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("bend", "bent", "bent", "plier / se courber")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("bereave", "bereft / bereaved", "bereft / bereaved", "déposséder / priver")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("bet", "bet", "bet", "parier")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("bid", "bid / bade", "bid / bidden", "offrir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("bleed", "bled", "bled", "saigner")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("blow", "blew", "blown", "souffler / gonfler")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("break", "broke", "broken", "casser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("breed", "bred", "bred", "élever (des animaux)")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("bring", "brought", "brought", "apporter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("broadcast", "broadcast", "broadcast", "diffuser / émettre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("build", "built", "built", "construire")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("burn", "burnt / burned", "burnt / burned", "brûler")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("burst", "burst", "burst", "éclater")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("buy", "bought", "bought", "acheter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("can", "could", "could", "pouvoir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("cast", "cast", "cast", "jeter / distribuer (rôles)")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("catch", "caught", "caught", "attraper")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("chide", "chid", "chiden", "gronder")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("choose", "chose", "chosen", "choisir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("cling", "clung", "clung", "s\'accrocher")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("clothe", "clad / clothed", "clad / clothed", "habiller / recouvrir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("come", "came", "come", "venir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("cost", "cost", "cost", "coûter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("creep", "crept", "crept", "ramper")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("cut", "cut", "cut", "couper")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("deal", "dealt", "dealt", "distribuer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("dig", "dug", "dug", "creuser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("dive", "dived", "dived / dove", "plonger")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("do", "did", "done", "faire")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("draw", "drew", "drawn", "dessiner / tirer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("dream", "dreamt / dreamed", "dreamt / dreamed", "rêver")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("drink", "drank", "drunk", "boire")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("drive", "drove", "driven", "conduire")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("dwell", "dwelt", "dwelt / dwelled", "habiter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("eat", "ate", "eaten", "manger")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("fall", "fell", "fallen", "tomber")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("feed", "fed", "fed", "nourrir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("feel", "felt", "felt", "se sentir / ressentir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("fight", "fought", "fought", "se battre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("find", "found", "found", "trouver")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("flee", "fled", "fled", "s\'enfuir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("fling", "flung", "flung", "lancer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("fly", "flew", "flown", "voler")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("forbid", "forbade", "forbidden", "interdire")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("forecast", "forecast", "forecast", "prévoir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("foresee", "foresaw", "foreseen", "prévoir / présentir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("forget", "forgot", "forgotten / forgot", "oublier")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("forgive", "forgave", "forgiven", "pardonner")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("forsake", "forsook", "forsaken", "abandonner")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("freeze", "froze", "frozen", "geler")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("get", "got", "gotten / got", "obtenir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("give", "gave", "given", "donner")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("go", "went", "gone", "aller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("grind", "ground", "ground", "moudre / opprimer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("grow", "grew", "grown", "grandir / pousser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("hang", "hung", "hung", "tenir / pendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("have", "had", "had", "avoir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("hear", "heard", "heard", "entendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("hide", "hid", "hidden", "cacher")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("hit", "hit", "hit", "taper / appuyer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("hold", "held", "held", "tenir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("hurt", "hurt", "hurt", "blesser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("keep", "kept", "kept", "garder")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("kneel", "knelt / knelled", "knelt / kneeled", "s\'agenouiller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("know", "knew", "known", "connaître / savoir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("lay", "laid", "laid", "poser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("lead", "led", "led", "mener / guider")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("lean", "leant / leaned", "leant / leaned", "s\'incliner / se pencher")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("leap", "leapt / leaped", "leapt / leaped", "sauter / bondir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("learn", "learnt", "learnt", "apprendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("leave", "left", "left", "laisser / quitter / partir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("lend", "lent", "lent", "prêter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("let", "let", "let", "permettre / louer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("lie", "lay", "lain", "s\'allonger")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("light", "lit / lighted", "lit / lighted", "allumer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("lose", "lost", "lost", "perdre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("make", "made", "made", "fabriquer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("mean", "meant", "meant", "signifier")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("meet", "met", "met", "rencontrer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("mow", "mowed", "mowed / mown", "tondre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("offset", "offset", "offset", "compenser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("overcome", "overcame", "overcome", "surmonter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("partake", "partook", "partaken", "prendre part à")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("pay", "paid", "paid", "payer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("plead", "pled / pleaded", "pled / pleaded", "supplier / plaider")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("preset", "preset", "preset", "programmer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("prove", "proved", "proven / proved", "prouver")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("put", "put", "put", "mettre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("quit", "quit", "quit", "quitter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("read", "read", "read", "lire")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("relay", "relaid", "relaid", "relayer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("rend", "rent", "rent", "déchirer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("rid", "rid", "rid", "débarrasser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("ride", "rode", "ridden", "monter (vélo, cheval)")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("ring", "rang", "rung", "sonner / téléphoner")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("rise", "rose", "risen", "lever")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("run", "ran", "run", "courir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("saw", "saw / sawed", "sawn / sawed", "scier")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("say", "said", "said", "dire")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("see", "saw", "seen", "voir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("seek", "sought", "sought", "chercher")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("sell", "sold", "sold", "vendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("send", "sent", "sent", "envoyer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("set", "set", "set", "fixer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("shake", "shook", "shaken", "secouer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("shed", "shed", "shed", "répandre / laisser tomber")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("shine", "shone", "shone", "briller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("shoe", "shod", "shod", "chausser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("shoot", "shot", "shot", "tirer / fusiller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("show", "showed", "shown", "montrer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("shut", "shut", "shut", "fermer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("sing", "sang", "sung", "chanter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("sink", "sank / sunk", "sunk / sunken", "couler")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("sit", "sat", "sat", "s\'asseoir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("slay", "slew", "slain", "tuer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("sleep", "slept", "slept", "dormir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("slide", "slid", "slid", "glisser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("slink", "slunk / slinked", "slunk / slinked", "s\'en aller furtivement")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("slit", "slit", "slit", "fendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("smell", "smelt", "smelt", "sentir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("sow", "sowed", "sown / sowed", "semer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("speak", "spoke", "spoken", "parler")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("speed", "sped", "sped", "aller vite")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("spell", "spelt", "spelt", "épeler / orthographier")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("spend", "spent", "spent", "dépenser / passer du temps")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("spill", "spilt / spilled", "spilt / spilled", "renverser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("spin", "spun", "spun", "tourner / faire tourner")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("spit", "spat / spit", "spat / spit", "cracher")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("split", "split", "split", "fendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("spoil", "spoilt", "spoilt", "gâcher / gâter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("spread", "spread", "spread", "répandre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("spring", "sprang", "sprung", "surgir / jaillir / bondir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("stand", "stood", "stood", "être debout")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("steal", "stole", "stolen", "voler / dérober")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("stick", "stuck", "stuck", "coller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("sting", "stung", "stung", "piquer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("stink", "stank", "stunk", "puer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("strew", "strewed", "strewn / strewed", "éparpiller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("strike", "struck", "stricken / struck", "frapper")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("strive", "strove", "striven", "s\'efforcer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("swear", "swore", "sworn", "jurer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("sweat", "sweat / sweated", "sweat / sweated", "suer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("sweep", "swept", "swept", "balayer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("swell", "swelled", "swollen / swelled", "gonfler / enfler")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("swim", "swam", "swum", "nager")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("swing", "swung", "swung", "se balancer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("take", "took", "taken", "prendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("teach", "taught", "taught", "enseigner")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("tear", "tore", "torn", "déchirer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("tell", "told", "told", "dire / raconter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("think", "thought", "thought", "penser")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("thrive", "throve / thrived", "thriven / thrived", "prospérer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("throw", "threw", "thrown", "jeter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("thrust", "thrust", "thrust", "enfoncer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("tread", "trod", "trodden", "piétiner quelque chose")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("typeset", "typeset", "typeset", "composer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("undergo", "underwent", "undergone", "subir")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("understand", "understood", "understood", "comprendre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("wake", "woke", "woken", "réveiller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("wear", "wore", "worn", "porter (avoir sur soi)")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("weep", "wept", "wept", "pleurer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("wet", "wet / wetted", "wet / wetted", "mouiller")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("win", "won", "won", "gagner")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("wind", "wound", "wound", "enrouler / remonter")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("withdraw", "withdrew", "withdrawn", "se retirer")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("wring", "wrung", "wrung", "tordre")');
$db->exec('INSERT INTO verbs(infinitive, preterit, pastPart, french) VALUES("write", "wrote", "written", "écrire")');
