INSERT INTO preterits(value, infinitive_id) VALUES('abode', (SELECT id FROM infinitives WHERE value='abide'));
INSERT INTO preterits(value, infinitive_id) VALUES('arose', (SELECT id FROM infinitives WHERE value='arise'));
INSERT INTO preterits(value, infinitive_id) VALUES('awoke', (SELECT id FROM infinitives WHERE value='awake'));
INSERT INTO preterits(value, infinitive_id) VALUES('was,were', (SELECT id FROM infinitives WHERE value='be'));
INSERT INTO preterits(value, infinitive_id) VALUES('bore', (SELECT id FROM infinitives WHERE value='bear'));
INSERT INTO preterits(value, infinitive_id) VALUES('beat', (SELECT id FROM infinitives WHERE value='beat'));
INSERT INTO preterits(value, infinitive_id) VALUES('became', (SELECT id FROM infinitives WHERE value='become'));
INSERT INTO preterits(value, infinitive_id) VALUES('begat', (SELECT id FROM infinitives WHERE value='beget')); INSERT INTO preterits(value, infinitive_id) VALUES('begot', (SELECT id FROM infinitives WHERE value='beget'));
INSERT INTO preterits(value, infinitive_id) VALUES('began', (SELECT id FROM infinitives WHERE value='begin'));
INSERT INTO preterits(value, infinitive_id) VALUES('bent', (SELECT id FROM infinitives WHERE value='bend'));
INSERT INTO preterits(value, infinitive_id) VALUES('bereft', (SELECT id FROM infinitives WHERE value='bereave')); INSERT INTO preterits(value, infinitive_id) VALUES('bereaved', (SELECT id FROM infinitives WHERE value='bereave'));
INSERT INTO preterits(value, infinitive_id) VALUES('bet', (SELECT id FROM infinitives WHERE value='bet'));
INSERT INTO preterits(value, infinitive_id) VALUES('bid', (SELECT id FROM infinitives WHERE value='bid')); INSERT INTO preterits(value, infinitive_id) VALUES('bade', (SELECT id FROM infinitives WHERE value='bid'));
INSERT INTO preterits(value, infinitive_id) VALUES('bound', (SELECT id FROM infinitives WHERE value='bind'));
INSERT INTO preterits(value, infinitive_id) VALUES('bite', (SELECT id FROM infinitives WHERE value='bite'));
INSERT INTO preterits(value, infinitive_id) VALUES('bled', (SELECT id FROM infinitives WHERE value='bleed'));
INSERT INTO preterits(value, infinitive_id) VALUES('blew', (SELECT id FROM infinitives WHERE value='blow'));
INSERT INTO preterits(value, infinitive_id) VALUES('broke', (SELECT id FROM infinitives WHERE value='break'));
INSERT INTO preterits(value, infinitive_id) VALUES('bred', (SELECT id FROM infinitives WHERE value='breed'));
INSERT INTO preterits(value, infinitive_id) VALUES('brought', (SELECT id FROM infinitives WHERE value='bring'));
INSERT INTO preterits(value, infinitive_id) VALUES('broadcast', (SELECT id FROM infinitives WHERE value='broadcast'));
INSERT INTO preterits(value, infinitive_id) VALUES('built', (SELECT id FROM infinitives WHERE value='build'));
INSERT INTO preterits(value, infinitive_id) VALUES('burnt', (SELECT id FROM infinitives WHERE value='burn')); INSERT INTO preterits(value, infinitive_id) VALUES('burned', (SELECT id FROM infinitives WHERE value='burn'));
INSERT INTO preterits(value, infinitive_id) VALUES('burst', (SELECT id FROM infinitives WHERE value='burst'));
INSERT INTO preterits(value, infinitive_id) VALUES('bought', (SELECT id FROM infinitives WHERE value='buy'));
INSERT INTO preterits(value, infinitive_id) VALUES('could', (SELECT id FROM infinitives WHERE value='can'));
INSERT INTO preterits(value, infinitive_id) VALUES('cast', (SELECT id FROM infinitives WHERE value='cast'));
INSERT INTO preterits(value, infinitive_id) VALUES('caught', (SELECT id FROM infinitives WHERE value='catch'));
INSERT INTO preterits(value, infinitive_id) VALUES('chid', (SELECT id FROM infinitives WHERE value='chide'));
INSERT INTO preterits(value, infinitive_id) VALUES('chose', (SELECT id FROM infinitives WHERE value='choose'));
INSERT INTO preterits(value, infinitive_id) VALUES('clung', (SELECT id FROM infinitives WHERE value='cling'));
INSERT INTO preterits(value, infinitive_id) VALUES('clad', (SELECT id FROM infinitives WHERE value='clothe')); INSERT INTO preterits(value, infinitive_id) VALUES('clothed', (SELECT id FROM infinitives WHERE value='clothe'));
INSERT INTO preterits(value, infinitive_id) VALUES('came', (SELECT id FROM infinitives WHERE value='come'));
INSERT INTO preterits(value, infinitive_id) VALUES('cost', (SELECT id FROM infinitives WHERE value='cost'));
INSERT INTO preterits(value, infinitive_id) VALUES('crept', (SELECT id FROM infinitives WHERE value='creep'));
INSERT INTO preterits(value, infinitive_id) VALUES('cut', (SELECT id FROM infinitives WHERE value='cut'));
INSERT INTO preterits(value, infinitive_id) VALUES('dealt', (SELECT id FROM infinitives WHERE value='deal'));
INSERT INTO preterits(value, infinitive_id) VALUES('dug', (SELECT id FROM infinitives WHERE value='dig'));
INSERT INTO preterits(value, infinitive_id) VALUES('dived', (SELECT id FROM infinitives WHERE value='dive'));
INSERT INTO preterits(value, infinitive_id) VALUES('did', (SELECT id FROM infinitives WHERE value='do'));
INSERT INTO preterits(value, infinitive_id) VALUES('drew', (SELECT id FROM infinitives WHERE value='draw'));
INSERT INTO preterits(value, infinitive_id) VALUES('dreamt', (SELECT id FROM infinitives WHERE value='dream')); INSERT INTO preterits(value, infinitive_id) VALUES('dreamed', (SELECT id FROM infinitives WHERE value='dream'));
INSERT INTO preterits(value, infinitive_id) VALUES('drank', (SELECT id FROM infinitives WHERE value='drink'));
INSERT INTO preterits(value, infinitive_id) VALUES('drove', (SELECT id FROM infinitives WHERE value='drive'));
INSERT INTO preterits(value, infinitive_id) VALUES('dwelt', (SELECT id FROM infinitives WHERE value='dwell'));
INSERT INTO preterits(value, infinitive_id) VALUES('ate', (SELECT id FROM infinitives WHERE value='eat'));
INSERT INTO preterits(value, infinitive_id) VALUES('fell', (SELECT id FROM infinitives WHERE value='fall'));
INSERT INTO preterits(value, infinitive_id) VALUES('fed', (SELECT id FROM infinitives WHERE value='feed'));
INSERT INTO preterits(value, infinitive_id) VALUES('felt', (SELECT id FROM infinitives WHERE value='feel'));
INSERT INTO preterits(value, infinitive_id) VALUES('fought', (SELECT id FROM infinitives WHERE value='fight'));
INSERT INTO preterits(value, infinitive_id) VALUES('found', (SELECT id FROM infinitives WHERE value='find'));
INSERT INTO preterits(value, infinitive_id) VALUES('fled', (SELECT id FROM infinitives WHERE value='flee'));
INSERT INTO preterits(value, infinitive_id) VALUES('flung', (SELECT id FROM infinitives WHERE value='fling'));
INSERT INTO preterits(value, infinitive_id) VALUES('flew', (SELECT id FROM infinitives WHERE value='fly'));
INSERT INTO preterits(value, infinitive_id) VALUES('forbade', (SELECT id FROM infinitives WHERE value='forbid'));
INSERT INTO preterits(value, infinitive_id) VALUES('forecast', (SELECT id FROM infinitives WHERE value='forecast'));
INSERT INTO preterits(value, infinitive_id) VALUES('foresaw', (SELECT id FROM infinitives WHERE value='foresee'));
INSERT INTO preterits(value, infinitive_id) VALUES('forgot', (SELECT id FROM infinitives WHERE value='forget'));
INSERT INTO preterits(value, infinitive_id) VALUES('forgave', (SELECT id FROM infinitives WHERE value='forgive'));
INSERT INTO preterits(value, infinitive_id) VALUES('forsook', (SELECT id FROM infinitives WHERE value='forsake'));
INSERT INTO preterits(value, infinitive_id) VALUES('froze', (SELECT id FROM infinitives WHERE value='freeze'));
INSERT INTO preterits(value, infinitive_id) VALUES('got', (SELECT id FROM infinitives WHERE value='get'));
INSERT INTO preterits(value, infinitive_id) VALUES('gave', (SELECT id FROM infinitives WHERE value='give'));
INSERT INTO preterits(value, infinitive_id) VALUES('went', (SELECT id FROM infinitives WHERE value='go'));
INSERT INTO preterits(value, infinitive_id) VALUES('ground', (SELECT id FROM infinitives WHERE value='grind'));
INSERT INTO preterits(value, infinitive_id) VALUES('grew', (SELECT id FROM infinitives WHERE value='grow'));
INSERT INTO preterits(value, infinitive_id) VALUES('hung', (SELECT id FROM infinitives WHERE value='hang'));
INSERT INTO preterits(value, infinitive_id) VALUES('had', (SELECT id FROM infinitives WHERE value='have'));
INSERT INTO preterits(value, infinitive_id) VALUES('heard', (SELECT id FROM infinitives WHERE value='hear'));
INSERT INTO preterits(value, infinitive_id) VALUES('hove', (SELECT id FROM infinitives WHERE value='heave'));
INSERT INTO preterits(value, infinitive_id) VALUES('hid', (SELECT id FROM infinitives WHERE value='hide'));
INSERT INTO preterits(value, infinitive_id) VALUES('hit', (SELECT id FROM infinitives WHERE value='hit'));
INSERT INTO preterits(value, infinitive_id) VALUES('held', (SELECT id FROM infinitives WHERE value='hold'));
INSERT INTO preterits(value, infinitive_id) VALUES('hurt', (SELECT id FROM infinitives WHERE value='hurt'));
INSERT INTO preterits(value, infinitive_id) VALUES('kept', (SELECT id FROM infinitives WHERE value='keep'));
INSERT INTO preterits(value, infinitive_id) VALUES('knelt', (SELECT id FROM infinitives WHERE value='kneel'));
INSERT INTO preterits(value, infinitive_id) VALUES('knit', (SELECT id FROM infinitives WHERE value='knit'));
INSERT INTO preterits(value, infinitive_id) VALUES('knew', (SELECT id FROM infinitives WHERE value='know'));
INSERT INTO preterits(value, infinitive_id) VALUES('laid', (SELECT id FROM infinitives WHERE value='lay'));
INSERT INTO preterits(value, infinitive_id) VALUES('led', (SELECT id FROM infinitives WHERE value='lead'));
INSERT INTO preterits(value, infinitive_id) VALUES('leant', (SELECT id FROM infinitives WHERE value='lean')); INSERT INTO preterits(value, infinitive_id) VALUES('leaned', (SELECT id FROM infinitives WHERE value='leap'));
INSERT INTO preterits(value, infinitive_id) VALUES('leapt', (SELECT id FROM infinitives WHERE value='leap')); INSERT INTO preterits(value, infinitive_id) VALUES('leaped', (SELECT id FROM infinitives WHERE value='leap'));
INSERT INTO preterits(value, infinitive_id) VALUES('learnt', (SELECT id FROM infinitives WHERE value='learn'));
INSERT INTO preterits(value, infinitive_id) VALUES('left', (SELECT id FROM infinitives WHERE value='leave'));
INSERT INTO preterits(value, infinitive_id) VALUES('lent', (SELECT id FROM infinitives WHERE value='lend'));
INSERT INTO preterits(value, infinitive_id) VALUES('let', (SELECT id FROM infinitives WHERE value='let'));
INSERT INTO preterits(value, infinitive_id) VALUES('lay', (SELECT id FROM infinitives WHERE value='lie'));
INSERT INTO preterits(value, infinitive_id) VALUES('lit', (SELECT id FROM infinitives WHERE value='light')); INSERT INTO preterits(value, infinitive_id) VALUES('lighted', (SELECT id FROM infinitives WHERE value='light'));
INSERT INTO preterits(value, infinitive_id) VALUES('lost', (SELECT id FROM infinitives WHERE value='lose'));
INSERT INTO preterits(value, infinitive_id) VALUES('made', (SELECT id FROM infinitives WHERE value='make'));
INSERT INTO preterits(value, infinitive_id) VALUES('meant', (SELECT id FROM infinitives WHERE value='mean'));
INSERT INTO preterits(value, infinitive_id) VALUES('met', (SELECT id FROM infinitives WHERE value='meet'));
INSERT INTO preterits(value, infinitive_id) VALUES('mowed', (SELECT id FROM infinitives WHERE value='mow'));
INSERT INTO preterits(value, infinitive_id) VALUES('offset', (SELECT id FROM infinitives WHERE value='offset'));
INSERT INTO preterits(value, infinitive_id) VALUES('overcame', (SELECT id FROM infinitives WHERE value='overcome'));
INSERT INTO preterits(value, infinitive_id) VALUES('partook', (SELECT id FROM infinitives WHERE value='partake'));
INSERT INTO preterits(value, infinitive_id) VALUES('paid', (SELECT id FROM infinitives WHERE value='pay'));
INSERT INTO preterits(value, infinitive_id) VALUES('pled', (SELECT id FROM infinitives WHERE value='plead')); INSERT INTO preterits(value, infinitive_id) VALUES('pleaded', (SELECT id FROM infinitives WHERE value='plead'));
INSERT INTO preterits(value, infinitive_id) VALUES('preset', (SELECT id FROM infinitives WHERE value='preset'));
INSERT INTO preterits(value, infinitive_id) VALUES('proved', (SELECT id FROM infinitives WHERE value='prove'));
INSERT INTO preterits(value, infinitive_id) VALUES('put', (SELECT id FROM infinitives WHERE value='put'));
INSERT INTO preterits(value, infinitive_id) VALUES('quit', (SELECT id FROM infinitives WHERE value='quit'));
INSERT INTO preterits(value, infinitive_id) VALUES('read', (SELECT id FROM infinitives WHERE value='read'));
INSERT INTO preterits(value, infinitive_id) VALUES('relaid', (SELECT id FROM infinitives WHERE value='relay'));
INSERT INTO preterits(value, infinitive_id) VALUES('rent', (SELECT id FROM infinitives WHERE value='rend'));
INSERT INTO preterits(value, infinitive_id) VALUES('rid', (SELECT id FROM infinitives WHERE value='rid'));
INSERT INTO preterits(value, infinitive_id) VALUES('rode', (SELECT id FROM infinitives WHERE value='ride'));
INSERT INTO preterits(value, infinitive_id) VALUES('rang', (SELECT id FROM infinitives WHERE value='ring'));
INSERT INTO preterits(value, infinitive_id) VALUES('rose', (SELECT id FROM infinitives WHERE value='rise'));
INSERT INTO preterits(value, infinitive_id) VALUES('ran', (SELECT id FROM infinitives WHERE value='run'));
INSERT INTO preterits(value, infinitive_id) VALUES('saw', (SELECT id FROM infinitives WHERE value='saw')); INSERT INTO preterits(value, infinitive_id) VALUES('sawed', (SELECT id FROM infinitives WHERE value='saw'));
INSERT INTO preterits(value, infinitive_id) VALUES('said', (SELECT id FROM infinitives WHERE value='say'));
INSERT INTO preterits(value, infinitive_id) VALUES('saw', (SELECT id FROM infinitives WHERE value='see'));
INSERT INTO preterits(value, infinitive_id) VALUES('sought', (SELECT id FROM infinitives WHERE value='seek'));
INSERT INTO preterits(value, infinitive_id) VALUES('sold', (SELECT id FROM infinitives WHERE value='sell'));
INSERT INTO preterits(value, infinitive_id) VALUES('sent', (SELECT id FROM infinitives WHERE value='send'));
INSERT INTO preterits(value, infinitive_id) VALUES('set', (SELECT id FROM infinitives WHERE value='set'));
INSERT INTO preterits(value, infinitive_id) VALUES('sewed', (SELECT id FROM infinitives WHERE value='sew'));
INSERT INTO preterits(value, infinitive_id) VALUES('shook', (SELECT id FROM infinitives WHERE value='shake'));
INSERT INTO preterits(value, infinitive_id) VALUES('sheared', (SELECT id FROM infinitives WHERE value='shear'));
INSERT INTO preterits(value, infinitive_id) VALUES('shed', (SELECT id FROM infinitives WHERE value='shed'));
INSERT INTO preterits(value, infinitive_id) VALUES('shone', (SELECT id FROM infinitives WHERE value='shine'));
INSERT INTO preterits(value, infinitive_id) VALUES('shod', (SELECT id FROM infinitives WHERE value='shoe'));
INSERT INTO preterits(value, infinitive_id) VALUES('shot', (SELECT id FROM infinitives WHERE value='shoot'));
INSERT INTO preterits(value, infinitive_id) VALUES('showed', (SELECT id FROM infinitives WHERE value='show'));
INSERT INTO preterits(value, infinitive_id) VALUES('shrank', (SELECT id FROM infinitives WHERE value='shrink')); INSERT INTO preterits(value, infinitive_id) VALUES('shrunk', (SELECT id FROM infinitives WHERE value='shrink'));
INSERT INTO preterits(value, infinitive_id) VALUES('shut', (SELECT id FROM infinitives WHERE value='shut'));
INSERT INTO preterits(value, infinitive_id) VALUES('sang', (SELECT id FROM infinitives WHERE value='sing'));
INSERT INTO preterits(value, infinitive_id) VALUES('sank', (SELECT id FROM infinitives WHERE value='sink')); INSERT INTO preterits(value, infinitive_id) VALUES('sunk', (SELECT id FROM infinitives WHERE value='sink'));
INSERT INTO preterits(value, infinitive_id) VALUES('sat', (SELECT id FROM infinitives WHERE value='sit'));
INSERT INTO preterits(value, infinitive_id) VALUES('slew', (SELECT id FROM infinitives WHERE value='slay'));
INSERT INTO preterits(value, infinitive_id) VALUES('slept', (SELECT id FROM infinitives WHERE value='sleep'));
INSERT INTO preterits(value, infinitive_id) VALUES('slid', (SELECT id FROM infinitives WHERE value='slide'));
INSERT INTO preterits(value, infinitive_id) VALUES('slung', (SELECT id FROM infinitives WHERE value='sling'));
INSERT INTO preterits(value, infinitive_id) VALUES('slunk', (SELECT id FROM infinitives WHERE value='slink')); INSERT INTO preterits(value, infinitive_id) VALUES('slinked', (SELECT id FROM infinitives WHERE value='slink'));
INSERT INTO preterits(value, infinitive_id) VALUES('slit', (SELECT id FROM infinitives WHERE value='slit'));
INSERT INTO preterits(value, infinitive_id) VALUES('smelt', (SELECT id FROM infinitives WHERE value='smell'));
INSERT INTO preterits(value, infinitive_id) VALUES('sowed', (SELECT id FROM infinitives WHERE value='sow'));
INSERT INTO preterits(value, infinitive_id) VALUES('spoke', (SELECT id FROM infinitives WHERE value='speak'));
INSERT INTO preterits(value, infinitive_id) VALUES('sped', (SELECT id FROM infinitives WHERE value='speed'));
INSERT INTO preterits(value, infinitive_id) VALUES('spelt', (SELECT id FROM infinitives WHERE value='spell'));
INSERT INTO preterits(value, infinitive_id) VALUES('spent', (SELECT id FROM infinitives WHERE value='spend'));
INSERT INTO preterits(value, infinitive_id) VALUES('spilt', (SELECT id FROM infinitives WHERE value='spill')); INSERT INTO preterits(value, infinitive_id) VALUES('spilled', (SELECT id FROM infinitives WHERE value='spill'));
INSERT INTO preterits(value, infinitive_id) VALUES('spun', (SELECT id FROM infinitives WHERE value='spin'));
INSERT INTO preterits(value, infinitive_id) VALUES('spat', (SELECT id FROM infinitives WHERE value='spit')); INSERT INTO preterits(value, infinitive_id) VALUES('spit', (SELECT id FROM infinitives WHERE value='spit'));
INSERT INTO preterits(value, infinitive_id) VALUES('split', (SELECT id FROM infinitives WHERE value='split'));
INSERT INTO preterits(value, infinitive_id) VALUES('spoilt', (SELECT id FROM infinitives WHERE value='spoil'));
INSERT INTO preterits(value, infinitive_id) VALUES('spread', (SELECT id FROM infinitives WHERE value='spread'));
INSERT INTO preterits(value, infinitive_id) VALUES('sprang', (SELECT id FROM infinitives WHERE value='spring'));
INSERT INTO preterits(value, infinitive_id) VALUES('stood', (SELECT id FROM infinitives WHERE value='stand'));
INSERT INTO preterits(value, infinitive_id) VALUES('stole', (SELECT id FROM infinitives WHERE value='steal'));
INSERT INTO preterits(value, infinitive_id) VALUES('stuck', (SELECT id FROM infinitives WHERE value='stick'));
INSERT INTO preterits(value, infinitive_id) VALUES('stung', (SELECT id FROM infinitives WHERE value='sting'));
INSERT INTO preterits(value, infinitive_id) VALUES('stank', (SELECT id FROM infinitives WHERE value='stink'));
INSERT INTO preterits(value, infinitive_id) VALUES('strewed', (SELECT id FROM infinitives WHERE value='strew'));
INSERT INTO preterits(value, infinitive_id) VALUES('strode', (SELECT id FROM infinitives WHERE value='strinde'));
INSERT INTO preterits(value, infinitive_id) VALUES('struck', (SELECT id FROM infinitives WHERE value='strike'));
INSERT INTO preterits(value, infinitive_id) VALUES('strung', (SELECT id FROM infinitives WHERE value='string'));
INSERT INTO preterits(value, infinitive_id) VALUES('strove', (SELECT id FROM infinitives WHERE value='strive'));
INSERT INTO preterits(value, infinitive_id) VALUES('swore', (SELECT id FROM infinitives WHERE value='swear'));
INSERT INTO preterits(value, infinitive_id) VALUES('sweat', (SELECT id FROM infinitives WHERE value='sweat')); INSERT INTO preterits(value, infinitive_id) VALUES('sweated', (SELECT id FROM infinitives WHERE value='sweat'));
INSERT INTO preterits(value, infinitive_id) VALUES('swept', (SELECT id FROM infinitives WHERE value='sweep'));
INSERT INTO preterits(value, infinitive_id) VALUES('swelled', (SELECT id FROM infinitives WHERE value='swell'));
INSERT INTO preterits(value, infinitive_id) VALUES('swam', (SELECT id FROM infinitives WHERE value='swim'));
INSERT INTO preterits(value, infinitive_id) VALUES('swung', (SELECT id FROM infinitives WHERE value='swing'));
INSERT INTO preterits(value, infinitive_id) VALUES('took', (SELECT id FROM infinitives WHERE value='take'));
INSERT INTO preterits(value, infinitive_id) VALUES('taught', (SELECT id FROM infinitives WHERE value='teach'));
INSERT INTO preterits(value, infinitive_id) VALUES('tore', (SELECT id FROM infinitives WHERE value='tear'));
INSERT INTO preterits(value, infinitive_id) VALUES('told', (SELECT id FROM infinitives WHERE value='tell'));
INSERT INTO preterits(value, infinitive_id) VALUES('thought', (SELECT id FROM infinitives WHERE value='think'));
INSERT INTO preterits(value, infinitive_id) VALUES('throve', (SELECT id FROM infinitives WHERE value='thrive')); INSERT INTO preterits(value, infinitive_id) VALUES('thrived', (SELECT id FROM infinitives WHERE value='thrive'));
INSERT INTO preterits(value, infinitive_id) VALUES('threw', (SELECT id FROM infinitives WHERE value='throw'));
INSERT INTO preterits(value, infinitive_id) VALUES('thrust', (SELECT id FROM infinitives WHERE value='thrust'));
INSERT INTO preterits(value, infinitive_id) VALUES('trod', (SELECT id FROM infinitives WHERE value='tread'));
INSERT INTO preterits(value, infinitive_id) VALUES('typeset', (SELECT id FROM infinitives WHERE value='typeset'));
INSERT INTO preterits(value, infinitive_id) VALUES('underwent', (SELECT id FROM infinitives WHERE value='undergo'));
INSERT INTO preterits(value, infinitive_id) VALUES('understood', (SELECT id FROM infinitives WHERE value='understand'));
INSERT INTO preterits(value, infinitive_id) VALUES('woke', (SELECT id FROM infinitives WHERE value='wake'));
INSERT INTO preterits(value, infinitive_id) VALUES('wore', (SELECT id FROM infinitives WHERE value='wear'));
INSERT INTO preterits(value, infinitive_id) VALUES('wove', (SELECT id FROM infinitives WHERE value='weave'));
INSERT INTO preterits(value, infinitive_id) VALUES('wed', (SELECT id FROM infinitives WHERE value='wed'));
INSERT INTO preterits(value, infinitive_id) VALUES('wept', (SELECT id FROM infinitives WHERE value='weep'));
INSERT INTO preterits(value, infinitive_id) VALUES('wet', (SELECT id FROM infinitives WHERE value='wet')); INSERT INTO preterits(value, infinitive_id) VALUES('wetted', (SELECT id FROM infinitives WHERE value='wet'));
INSERT INTO preterits(value, infinitive_id) VALUES('won', (SELECT id FROM infinitives WHERE value='win'));
INSERT INTO preterits(value, infinitive_id) VALUES('wound', (SELECT id FROM infinitives WHERE value='wind'));
INSERT INTO preterits(value, infinitive_id) VALUES('withdrew', (SELECT id FROM infinitives WHERE value='withdraw'));
INSERT INTO preterits(value, infinitive_id) VALUES('wrung', (SELECT id FROM infinitives WHERE value='wring'));
INSERT INTO preterits(value, infinitive_id) VALUES('wrote', (SELECT id FROM infinitives WHERE value='write'));