INSERT INTO past_participles(value, infinitive_id) VALUES('abode', (SELECT id FROM infinitives WHERE value='abide'));
INSERT INTO past_participles(value, infinitive_id) VALUES('arisen', (SELECT id FROM infinitives WHERE value='arise'));
INSERT INTO past_participles(value, infinitive_id) VALUES('awoken', (SELECT id FROM infinitives WHERE value='awake'));
INSERT INTO past_participles(value, infinitive_id) VALUES('been', (SELECT id FROM infinitives WHERE value='be'));
INSERT INTO past_participles(value, infinitive_id) VALUES('borne', (SELECT id FROM infinitives WHERE value='bear')); INSERT INTO past_participles(value, infinitive_id) VALUES('born', (SELECT id FROM infinitives WHERE value='bear'));
INSERT INTO past_participles(value, infinitive_id) VALUES('beaten', (SELECT id FROM infinitives WHERE value='beat'));
INSERT INTO past_participles(value, infinitive_id) VALUES('become', (SELECT id FROM infinitives WHERE value='become'));
INSERT INTO past_participles(value, infinitive_id) VALUES('begotten', (SELECT id FROM infinitives WHERE value='beget'));
INSERT INTO past_participles(value, infinitive_id) VALUES('begun', (SELECT id FROM infinitives WHERE value='begin'));
INSERT INTO past_participles(value, infinitive_id) VALUES('bent', (SELECT id FROM infinitives WHERE value='bend'));
INSERT INTO past_participles(value, infinitive_id) VALUES('bereft', (SELECT id FROM infinitives WHERE value='bereave')); INSERT INTO past_participles(value, infinitive_id) VALUES('bereaved', (SELECT id FROM infinitives WHERE value='bereave'));
INSERT INTO past_participles(value, infinitive_id) VALUES('bet', (SELECT id FROM infinitives WHERE value='bet'));
INSERT INTO past_participles(value, infinitive_id) VALUES('bid', (SELECT id FROM infinitives WHERE value='bid')); INSERT INTO past_participles(value, infinitive_id) VALUES('bidden', (SELECT id FROM infinitives WHERE value='bid'));
INSERT INTO past_participles(value, infinitive_id) VALUES('bound', (SELECT id FROM infinitives WHERE value='bind'));
INSERT INTO past_participles(value, infinitive_id) VALUES('bitten', (SELECT id FROM infinitives WHERE value='bite'));
INSERT INTO past_participles(value, infinitive_id) VALUES('bled', (SELECT id FROM infinitives WHERE value='bleed'));
INSERT INTO past_participles(value, infinitive_id) VALUES('blown', (SELECT id FROM infinitives WHERE value='blow'));
INSERT INTO past_participles(value, infinitive_id) VALUES('broken', (SELECT id FROM infinitives WHERE value='break'));
INSERT INTO past_participles(value, infinitive_id) VALUES('bred', (SELECT id FROM infinitives WHERE value='breed'));
INSERT INTO past_participles(value, infinitive_id) VALUES('brought', (SELECT id FROM infinitives WHERE value='bring'));
INSERT INTO past_participles(value, infinitive_id) VALUES('broadcast', (SELECT id FROM infinitives WHERE value='broadcast'));
INSERT INTO past_participles(value, infinitive_id) VALUES('built', (SELECT id FROM infinitives WHERE value='build'));
INSERT INTO past_participles(value, infinitive_id) VALUES('burnt', (SELECT id FROM infinitives WHERE value='burn')); INSERT INTO past_participles(value, infinitive_id) VALUES('burned', (SELECT id FROM infinitives WHERE value='burn'));
INSERT INTO past_participles(value, infinitive_id) VALUES('burst', (SELECT id FROM infinitives WHERE value='burst'));
INSERT INTO past_participles(value, infinitive_id) VALUES('bought', (SELECT id FROM infinitives WHERE value='buy'));
INSERT INTO past_participles(value, infinitive_id) VALUES('could', (SELECT id FROM infinitives WHERE value='can'));
INSERT INTO past_participles(value, infinitive_id) VALUES('cast', (SELECT id FROM infinitives WHERE value='cast'));
INSERT INTO past_participles(value, infinitive_id) VALUES('caught', (SELECT id FROM infinitives WHERE value='catch'));
INSERT INTO past_participles(value, infinitive_id) VALUES('chiden', (SELECT id FROM infinitives WHERE value='chide'));
INSERT INTO past_participles(value, infinitive_id) VALUES('chosen', (SELECT id FROM infinitives WHERE value='choose'));
INSERT INTO past_participles(value, infinitive_id) VALUES('clung', (SELECT id FROM infinitives WHERE value='cling'));
INSERT INTO past_participles(value, infinitive_id) VALUES('clad', (SELECT id FROM infinitives WHERE value='clothe')); INSERT INTO past_participles(value, infinitive_id) VALUES('clothed', (SELECT id FROM infinitives WHERE value='clothe'));
INSERT INTO past_participles(value, infinitive_id) VALUES('come', (SELECT id FROM infinitives WHERE value='come'));
INSERT INTO past_participles(value, infinitive_id) VALUES('cost', (SELECT id FROM infinitives WHERE value='cost'));
INSERT INTO past_participles(value, infinitive_id) VALUES('crept', (SELECT id FROM infinitives WHERE value='creep'));
INSERT INTO past_participles(value, infinitive_id) VALUES('cut', (SELECT id FROM infinitives WHERE value='cut'));
INSERT INTO past_participles(value, infinitive_id) VALUES('dealt', (SELECT id FROM infinitives WHERE value='deal'));
INSERT INTO past_participles(value, infinitive_id) VALUES('dug', (SELECT id FROM infinitives WHERE value='dig'));
INSERT INTO past_participles(value, infinitive_id) VALUES('dived', (SELECT id FROM infinitives WHERE value='dive')); INSERT INTO past_participles(value, infinitive_id) VALUES('dove', (SELECT id FROM infinitives WHERE value='dive'));
INSERT INTO past_participles(value, infinitive_id) VALUES('done', (SELECT id FROM infinitives WHERE value='do'));
INSERT INTO past_participles(value, infinitive_id) VALUES('drawn', (SELECT id FROM infinitives WHERE value='draw'));
INSERT INTO past_participles(value, infinitive_id) VALUES('dreamt', (SELECT id FROM infinitives WHERE value='dream')); INSERT INTO past_participles(value, infinitive_id) VALUES('dreamed', (SELECT id FROM infinitives WHERE value='dream'));
INSERT INTO past_participles(value, infinitive_id) VALUES('drunk', (SELECT id FROM infinitives WHERE value='drink'));
INSERT INTO past_participles(value, infinitive_id) VALUES('driven', (SELECT id FROM infinitives WHERE value='drive'));
INSERT INTO past_participles(value, infinitive_id) VALUES('dwelt', (SELECT id FROM infinitives WHERE value='dwell')); INSERT INTO past_participles(value, infinitive_id) VALUES('dwelled', (SELECT id FROM infinitives WHERE value='dwell'));
INSERT INTO past_participles(value, infinitive_id) VALUES('eaten', (SELECT id FROM infinitives WHERE value='eat'));
INSERT INTO past_participles(value, infinitive_id) VALUES('fallen', (SELECT id FROM infinitives WHERE value='fall'));
INSERT INTO past_participles(value, infinitive_id) VALUES('fed', (SELECT id FROM infinitives WHERE value='feed'));
INSERT INTO past_participles(value, infinitive_id) VALUES('felt', (SELECT id FROM infinitives WHERE value='feel'));
INSERT INTO past_participles(value, infinitive_id) VALUES('fought', (SELECT id FROM infinitives WHERE value='fight'));
INSERT INTO past_participles(value, infinitive_id) VALUES('found', (SELECT id FROM infinitives WHERE value='find'));
INSERT INTO past_participles(value, infinitive_id) VALUES('fled', (SELECT id FROM infinitives WHERE value='flee'));
INSERT INTO past_participles(value, infinitive_id) VALUES('flung', (SELECT id FROM infinitives WHERE value='fling'));
INSERT INTO past_participles(value, infinitive_id) VALUES('flown', (SELECT id FROM infinitives WHERE value='fly'));
INSERT INTO past_participles(value, infinitive_id) VALUES('forbidden', (SELECT id FROM infinitives WHERE value='forbid'));
INSERT INTO past_participles(value, infinitive_id) VALUES('forecast', (SELECT id FROM infinitives WHERE value='forecast'));
INSERT INTO past_participles(value, infinitive_id) VALUES('foreseen', (SELECT id FROM infinitives WHERE value='foresee'));
INSERT INTO past_participles(value, infinitive_id) VALUES('forgotten', (SELECT id FROM infinitives WHERE value='forget')); INSERT INTO past_participles(value, infinitive_id) VALUES('forgot', (SELECT id FROM infinitives WHERE value='forget'));
INSERT INTO past_participles(value, infinitive_id) VALUES('forgiven', (SELECT id FROM infinitives WHERE value='forgive'));
INSERT INTO past_participles(value, infinitive_id) VALUES('forsaken', (SELECT id FROM infinitives WHERE value='forsake'));
INSERT INTO past_participles(value, infinitive_id) VALUES('frozen', (SELECT id FROM infinitives WHERE value='freeze'));
INSERT INTO past_participles(value, infinitive_id) VALUES('gotten', (SELECT id FROM infinitives WHERE value='get')); INSERT INTO past_participles(value, infinitive_id) VALUES('got', (SELECT id FROM infinitives WHERE value='get'));
INSERT INTO past_participles(value, infinitive_id) VALUES('given', (SELECT id FROM infinitives WHERE value='give'));
INSERT INTO past_participles(value, infinitive_id) VALUES('gone', (SELECT id FROM infinitives WHERE value='go'));
INSERT INTO past_participles(value, infinitive_id) VALUES('ground', (SELECT id FROM infinitives WHERE value='grind'));
INSERT INTO past_participles(value, infinitive_id) VALUES('grown', (SELECT id FROM infinitives WHERE value='grow'));
INSERT INTO past_participles(value, infinitive_id) VALUES('hung', (SELECT id FROM infinitives WHERE value='hang'));
INSERT INTO past_participles(value, infinitive_id) VALUES('had', (SELECT id FROM infinitives WHERE value='have'));
INSERT INTO past_participles(value, infinitive_id) VALUES('heard', (SELECT id FROM infinitives WHERE value='hear'));
INSERT INTO past_participles(value, infinitive_id) VALUES('hove', (SELECT id FROM infinitives WHERE value='heave'));
INSERT INTO past_participles(value, infinitive_id) VALUES('hidden', (SELECT id FROM infinitives WHERE value='hide'));
INSERT INTO past_participles(value, infinitive_id) VALUES('hit', (SELECT id FROM infinitives WHERE value='hit'));
INSERT INTO past_participles(value, infinitive_id) VALUES('held', (SELECT id FROM infinitives WHERE value='hold'));
INSERT INTO past_participles(value, infinitive_id) VALUES('hurt', (SELECT id FROM infinitives WHERE value='hurt'));
INSERT INTO past_participles(value, infinitive_id) VALUES('kept', (SELECT id FROM infinitives WHERE value='keep'));
INSERT INTO past_participles(value, infinitive_id) VALUES('knelt', (SELECT id FROM infinitives WHERE value='kneel'));
INSERT INTO past_participles(value, infinitive_id) VALUES('knit', (SELECT id FROM infinitives WHERE value='knit'));
INSERT INTO past_participles(value, infinitive_id) VALUES('known', (SELECT id FROM infinitives WHERE value='know'));
INSERT INTO past_participles(value, infinitive_id) VALUES('laid', (SELECT id FROM infinitives WHERE value='lay'));
INSERT INTO past_participles(value, infinitive_id) VALUES('led', (SELECT id FROM infinitives WHERE value='lead'));
INSERT INTO past_participles(value, infinitive_id) VALUES('leant', (SELECT id FROM infinitives WHERE value='lean')); INSERT INTO past_participles(value, infinitive_id) VALUES('leaned', (SELECT id FROM infinitives WHERE value='lean'));
INSERT INTO past_participles(value, infinitive_id) VALUES('leapt', (SELECT id FROM infinitives WHERE value='leap')); INSERT INTO past_participles(value, infinitive_id) VALUES('leaped', (SELECT id FROM infinitives WHERE value='leap'));
INSERT INTO past_participles(value, infinitive_id) VALUES('learnt', (SELECT id FROM infinitives WHERE value='learn'));
INSERT INTO past_participles(value, infinitive_id) VALUES('left', (SELECT id FROM infinitives WHERE value='leave'));
INSERT INTO past_participles(value, infinitive_id) VALUES('lent', (SELECT id FROM infinitives WHERE value='lend'));
INSERT INTO past_participles(value, infinitive_id) VALUES('let', (SELECT id FROM infinitives WHERE value='let'));
INSERT INTO past_participles(value, infinitive_id) VALUES('lain', (SELECT id FROM infinitives WHERE value='lie'));
INSERT INTO past_participles(value, infinitive_id) VALUES('lit', (SELECT id FROM infinitives WHERE value='light')); INSERT INTO past_participles(value, infinitive_id) VALUES('lighted', (SELECT id FROM infinitives WHERE value='light'));
INSERT INTO past_participles(value, infinitive_id) VALUES('lost', (SELECT id FROM infinitives WHERE value='lose'));
INSERT INTO past_participles(value, infinitive_id) VALUES('made', (SELECT id FROM infinitives WHERE value='make'));
INSERT INTO past_participles(value, infinitive_id) VALUES('meant', (SELECT id FROM infinitives WHERE value='mean'));
INSERT INTO past_participles(value, infinitive_id) VALUES('met', (SELECT id FROM infinitives WHERE value='meet'));
INSERT INTO past_participles(value, infinitive_id) VALUES('mowed', (SELECT id FROM infinitives WHERE value='mow')); INSERT INTO past_participles(value, infinitive_id) VALUES('mown', (SELECT id FROM infinitives WHERE value='mow'));
INSERT INTO past_participles(value, infinitive_id) VALUES('offset', (SELECT id FROM infinitives WHERE value='offset'));
INSERT INTO past_participles(value, infinitive_id) VALUES('overcome', (SELECT id FROM infinitives WHERE value='overcome'));
INSERT INTO past_participles(value, infinitive_id) VALUES('partaken', (SELECT id FROM infinitives WHERE value='partake'));
INSERT INTO past_participles(value, infinitive_id) VALUES('paid', (SELECT id FROM infinitives WHERE value='pay'));
INSERT INTO past_participles(value, infinitive_id) VALUES('pled', (SELECT id FROM infinitives WHERE value='plead')); INSERT INTO past_participles(value, infinitive_id) VALUES('pleaded', (SELECT id FROM infinitives WHERE value='plead'));
INSERT INTO past_participles(value, infinitive_id) VALUES('preset', (SELECT id FROM infinitives WHERE value='preset'));
INSERT INTO past_participles(value, infinitive_id) VALUES('proven', (SELECT id FROM infinitives WHERE value='prove')); INSERT INTO past_participles(value, infinitive_id) VALUES('proved', (SELECT id FROM infinitives WHERE value='prove'));
INSERT INTO past_participles(value, infinitive_id) VALUES('put', (SELECT id FROM infinitives WHERE value='put'));
INSERT INTO past_participles(value, infinitive_id) VALUES('quit', (SELECT id FROM infinitives WHERE value='quit'));
INSERT INTO past_participles(value, infinitive_id) VALUES('read', (SELECT id FROM infinitives WHERE value='read'));
INSERT INTO past_participles(value, infinitive_id) VALUES('relaid', (SELECT id FROM infinitives WHERE value='relay'));
INSERT INTO past_participles(value, infinitive_id) VALUES('rent', (SELECT id FROM infinitives WHERE value='rend'));
INSERT INTO past_participles(value, infinitive_id) VALUES('rid', (SELECT id FROM infinitives WHERE value='rid'));
INSERT INTO past_participles(value, infinitive_id) VALUES('ridden', (SELECT id FROM infinitives WHERE value='ride'));
INSERT INTO past_participles(value, infinitive_id) VALUES('rung', (SELECT id FROM infinitives WHERE value='ring'));
INSERT INTO past_participles(value, infinitive_id) VALUES('risen', (SELECT id FROM infinitives WHERE value='rise'));
INSERT INTO past_participles(value, infinitive_id) VALUES('run', (SELECT id FROM infinitives WHERE value='run'));
INSERT INTO past_participles(value, infinitive_id) VALUES('sawn', (SELECT id FROM infinitives WHERE value='saw')); INSERT INTO past_participles(value, infinitive_id) VALUES('sawed', (SELECT id FROM infinitives WHERE value='saw'));
INSERT INTO past_participles(value, infinitive_id) VALUES('said', (SELECT id FROM infinitives WHERE value='say'));
INSERT INTO past_participles(value, infinitive_id) VALUES('seen', (SELECT id FROM infinitives WHERE value='see'));
INSERT INTO past_participles(value, infinitive_id) VALUES('sought', (SELECT id FROM infinitives WHERE value='seek'));
INSERT INTO past_participles(value, infinitive_id) VALUES('sold', (SELECT id FROM infinitives WHERE value='sell'));
INSERT INTO past_participles(value, infinitive_id) VALUES('sent', (SELECT id FROM infinitives WHERE value='send'));
INSERT INTO past_participles(value, infinitive_id) VALUES('set', (SELECT id FROM infinitives WHERE value='set'));
INSERT INTO past_participles(value, infinitive_id) VALUES('sewn', (SELECT id FROM infinitives WHERE value='sew'));
INSERT INTO past_participles(value, infinitive_id) VALUES('shaken', (SELECT id FROM infinitives WHERE value='shake'));
INSERT INTO past_participles(value, infinitive_id) VALUES('shorn', (SELECT id FROM infinitives WHERE value='shear'));
INSERT INTO past_participles(value, infinitive_id) VALUES('shed', (SELECT id FROM infinitives WHERE value='shed'));
INSERT INTO past_participles(value, infinitive_id) VALUES('shone', (SELECT id FROM infinitives WHERE value='shine'));
INSERT INTO past_participles(value, infinitive_id) VALUES('shod', (SELECT id FROM infinitives WHERE value='shoe'));
INSERT INTO past_participles(value, infinitive_id) VALUES('shot', (SELECT id FROM infinitives WHERE value='shoot'));
INSERT INTO past_participles(value, infinitive_id) VALUES('shown', (SELECT id FROM infinitives WHERE value='show'));
INSERT INTO past_participles(value, infinitive_id) VALUES('shrunk', (SELECT id FROM infinitives WHERE value='shrink')); INSERT INTO past_participles(value, infinitive_id) VALUES('shrunk', (SELECT id FROM infinitives WHERE value='shrink'));
INSERT INTO past_participles(value, infinitive_id) VALUES('shut', (SELECT id FROM infinitives WHERE value='shut'));
INSERT INTO past_participles(value, infinitive_id) VALUES('sung', (SELECT id FROM infinitives WHERE value='sing'));
INSERT INTO past_participles(value, infinitive_id) VALUES('sunk', (SELECT id FROM infinitives WHERE value='sink')); INSERT INTO past_participles(value, infinitive_id) VALUES('sunken', (SELECT id FROM infinitives WHERE value='sink'));
INSERT INTO past_participles(value, infinitive_id) VALUES('sat', (SELECT id FROM infinitives WHERE value='sit'));
INSERT INTO past_participles(value, infinitive_id) VALUES('slain', (SELECT id FROM infinitives WHERE value='slay'));
INSERT INTO past_participles(value, infinitive_id) VALUES('slept', (SELECT id FROM infinitives WHERE value='sleep'));
INSERT INTO past_participles(value, infinitive_id) VALUES('slid', (SELECT id FROM infinitives WHERE value='slide'));
INSERT INTO past_participles(value, infinitive_id) VALUES('slung', (SELECT id FROM infinitives WHERE value='sling'));
INSERT INTO past_participles(value, infinitive_id) VALUES('slunk', (SELECT id FROM infinitives WHERE value='slink')); INSERT INTO past_participles(value, infinitive_id) VALUES('slinked', (SELECT id FROM infinitives WHERE value='slink'));
INSERT INTO past_participles(value, infinitive_id) VALUES('slit', (SELECT id FROM infinitives WHERE value='slit'));
INSERT INTO past_participles(value, infinitive_id) VALUES('smelt', (SELECT id FROM infinitives WHERE value='smell'));
INSERT INTO past_participles(value, infinitive_id) VALUES('sown', (SELECT id FROM infinitives WHERE value='sow')); INSERT INTO past_participles(value, infinitive_id) VALUES('sowed', (SELECT id FROM infinitives WHERE value='sow'));
INSERT INTO past_participles(value, infinitive_id) VALUES('spoken', (SELECT id FROM infinitives WHERE value='speak'));
INSERT INTO past_participles(value, infinitive_id) VALUES('sped', (SELECT id FROM infinitives WHERE value='speed'));
INSERT INTO past_participles(value, infinitive_id) VALUES('spelt', (SELECT id FROM infinitives WHERE value='spell'));
INSERT INTO past_participles(value, infinitive_id) VALUES('spent', (SELECT id FROM infinitives WHERE value='spend'));
INSERT INTO past_participles(value, infinitive_id) VALUES('spilt', (SELECT id FROM infinitives WHERE value='spill')); INSERT INTO past_participles(value, infinitive_id) VALUES('spilled', (SELECT id FROM infinitives WHERE value='spill'));
INSERT INTO past_participles(value, infinitive_id) VALUES('spun', (SELECT id FROM infinitives WHERE value='spin'));
INSERT INTO past_participles(value, infinitive_id) VALUES('spat', (SELECT id FROM infinitives WHERE value='spit')); INSERT INTO past_participles(value, infinitive_id) VALUES('spit', (SELECT id FROM infinitives WHERE value='spit'));
INSERT INTO past_participles(value, infinitive_id) VALUES('split', (SELECT id FROM infinitives WHERE value='split'));
INSERT INTO past_participles(value, infinitive_id) VALUES('spoilt', (SELECT id FROM infinitives WHERE value='spoil'));
INSERT INTO past_participles(value, infinitive_id) VALUES('spread', (SELECT id FROM infinitives WHERE value='spread'));
INSERT INTO past_participles(value, infinitive_id) VALUES('sprung', (SELECT id FROM infinitives WHERE value='spring'));
INSERT INTO past_participles(value, infinitive_id) VALUES('stood', (SELECT id FROM infinitives WHERE value='stand'));
INSERT INTO past_participles(value, infinitive_id) VALUES('stolen', (SELECT id FROM infinitives WHERE value='steal'));
INSERT INTO past_participles(value, infinitive_id) VALUES('stuck', (SELECT id FROM infinitives WHERE value='stick'));
INSERT INTO past_participles(value, infinitive_id) VALUES('stung', (SELECT id FROM infinitives WHERE value='sting'));
INSERT INTO past_participles(value, infinitive_id) VALUES('stunk', (SELECT id FROM infinitives WHERE value='stink'));
INSERT INTO past_participles(value, infinitive_id) VALUES('strewn', (SELECT id FROM infinitives WHERE value='strew')); INSERT INTO past_participles(value, infinitive_id) VALUES('strewed', (SELECT id FROM infinitives WHERE value='strew'));
INSERT INTO past_participles(value, infinitive_id) VALUES('stridden', (SELECT id FROM infinitives WHERE value='strinde')); INSERT INTO past_participles(value, infinitive_id) VALUES('strode', (SELECT id FROM infinitives WHERE value='strinde'));
INSERT INTO past_participles(value, infinitive_id) VALUES('stricken', (SELECT id FROM infinitives WHERE value='strike')); INSERT INTO past_participles(value, infinitive_id) VALUES('struck', (SELECT id FROM infinitives WHERE value='strike'));
INSERT INTO past_participles(value, infinitive_id) VALUES('strung', (SELECT id FROM infinitives WHERE value='string'));
INSERT INTO past_participles(value, infinitive_id) VALUES('striven', (SELECT id FROM infinitives WHERE value='strive'));
INSERT INTO past_participles(value, infinitive_id) VALUES('sworn', (SELECT id FROM infinitives WHERE value='swear'));
INSERT INTO past_participles(value, infinitive_id) VALUES('sweat', (SELECT id FROM infinitives WHERE value='sweat')); INSERT INTO past_participles(value, infinitive_id) VALUES('sweated', (SELECT id FROM infinitives WHERE value='sweat'));
INSERT INTO past_participles(value, infinitive_id) VALUES('swept', (SELECT id FROM infinitives WHERE value='sweep'));
INSERT INTO past_participles(value, infinitive_id) VALUES('swollen', (SELECT id FROM infinitives WHERE value='swell')); INSERT INTO past_participles(value, infinitive_id) VALUES('swelled', (SELECT id FROM infinitives WHERE value='swell'));
INSERT INTO past_participles(value, infinitive_id) VALUES('swum', (SELECT id FROM infinitives WHERE value='swim'));
INSERT INTO past_participles(value, infinitive_id) VALUES('swung', (SELECT id FROM infinitives WHERE value='swing'));
INSERT INTO past_participles(value, infinitive_id) VALUES('taken', (SELECT id FROM infinitives WHERE value='take'));
INSERT INTO past_participles(value, infinitive_id) VALUES('taught', (SELECT id FROM infinitives WHERE value='teach'));
INSERT INTO past_participles(value, infinitive_id) VALUES('torn', (SELECT id FROM infinitives WHERE value='tear'));
INSERT INTO past_participles(value, infinitive_id) VALUES('told', (SELECT id FROM infinitives WHERE value='tell'));
INSERT INTO past_participles(value, infinitive_id) VALUES('thought', (SELECT id FROM infinitives WHERE value='think'));
INSERT INTO past_participles(value, infinitive_id) VALUES('thriven', (SELECT id FROM infinitives WHERE value='thrive')); INSERT INTO past_participles(value, infinitive_id) VALUES('thrived', (SELECT id FROM infinitives WHERE value='thrive'));
INSERT INTO past_participles(value, infinitive_id) VALUES('thrown', (SELECT id FROM infinitives WHERE value='throw'));
INSERT INTO past_participles(value, infinitive_id) VALUES('thrust', (SELECT id FROM infinitives WHERE value='thrust'));
INSERT INTO past_participles(value, infinitive_id) VALUES('trodden', (SELECT id FROM infinitives WHERE value='tread'));
INSERT INTO past_participles(value, infinitive_id) VALUES('typeset', (SELECT id FROM infinitives WHERE value='typeset'));
INSERT INTO past_participles(value, infinitive_id) VALUES('undergone', (SELECT id FROM infinitives WHERE value='undergo'));
INSERT INTO past_participles(value, infinitive_id) VALUES('understood', (SELECT id FROM infinitives WHERE value='understand'));
INSERT INTO past_participles(value, infinitive_id) VALUES('woken', (SELECT id FROM infinitives WHERE value='wake'));
INSERT INTO past_participles(value, infinitive_id) VALUES('worn', (SELECT id FROM infinitives WHERE value='wear'));
INSERT INTO past_participles(value, infinitive_id) VALUES('woven', (SELECT id FROM infinitives WHERE value='weave'));
INSERT INTO past_participles(value, infinitive_id) VALUES('wed', (SELECT id FROM infinitives WHERE value='wed'));
INSERT INTO past_participles(value, infinitive_id) VALUES('wept', (SELECT id FROM infinitives WHERE value='weep'));
INSERT INTO past_participles(value, infinitive_id) VALUES('wet', (SELECT id FROM infinitives WHERE value='wet')); INSERT INTO past_participles(value, infinitive_id) VALUES('wetted', (SELECT id FROM infinitives WHERE value='wet'));
INSERT INTO past_participles(value, infinitive_id) VALUES('won', (SELECT id FROM infinitives WHERE value='win'));
INSERT INTO past_participles(value, infinitive_id) VALUES('wound', (SELECT id FROM infinitives WHERE value='wind'));
INSERT INTO past_participles(value, infinitive_id) VALUES('withdrawn', (SELECT id FROM infinitives WHERE value='withdraw'));
INSERT INTO past_participles(value, infinitive_id) VALUES('wrung', (SELECT id FROM infinitives WHERE value='wring'));
INSERT INTO past_participles(value, infinitive_id) VALUES('written', (SELECT id FROM infinitives WHERE value='write'));